---

- name: Copy caddy script
  ansible.builtin.template:
    src: "caddy"
    dest: /usr/local/bin/caddy
    mode: 0755
    owner: root
    group: root

- name: Copy caddy-fix bash script
  ansible.builtin.template:
    src: "caddy-fix.sh"
    dest: /opt/
    mode: 0755
    owner: root
    group: root

- name: Copy caddy service
  ansible.builtin.template:
    src: "caddy.service"
    dest: /etc/systemd/system/caddy.service
    mode: 0644
    owner: root
    group: root
  notify:
    - restart caddy

- name: Ensure caddy service is restarted
  ansible.builtin.service:
    name: Caddy
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for caddy to become ready
  ansible.builtin.wait_for:
    host: "0.0.0.0"
    port: "80"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 3000
