---

- name: Setup group
  ansible.builtin.group:
    name: "{{ caddy_group }}"
    system: false

- name: Setup user
  ansible.builtin.user:
    name: "{{ caddy_user }}"
    system: false
    group: "{{ caddy_group }}"
