---

- name: restart caddy
  service:
    name: caddy
    state: restarted
    enabled: true

- name: reload caddy
  systemd:
    name: caddy
    state: reloaded

- name: start caddy
  systemd:
    name: caddy
    state: started
