---

- name: Restart caddy
  ansible.builtin.service:
    name: Caddy
    state: restarted
    enabled: true

- name: Reload caddy
  ansible.builtin.systemd:
    name: Caddy
    state: reloaded

- name: Start caddy
  ansible.builtin.systemd:
    name: Caddy
    state: started
